### ISSUE TITLE
Implementation plans for self-similarity

### ISSUE THREAD

**Issue by shunk031** [Gabrock94/pyaesthetics#4]
Hi @Gabrock94, thank you for the awesome repository.

Looing at [this code](https://github.com/Gabrock94/pyaesthetics/blob/master/pyaesthetics/selfsimilarity.py), the implementation appears to be in progress. Are there any plans for future implementation?

**Comment by Gabrock94** [comment]
Hi! 
Thanks for the feedback.

> Looing at [this code](https://github.com/Gabrock94/pyaesthetics/blob/master/pyaesthetics/selfsimilarity.py), the implementation appears to be in progress. Are there any plans for future implementation?
Actually yes. The problem is that I haven't been able to implement it properly on my first try and later on I got distracted by other things. Now I am implementing a couple different things for shapes detection, which have priority as we are using it for a thesis project. I will try to finish the self similarity soon after. 

I have also seen your fork/pull request. I will take a look at it in the coming days!

**Comment by shunk031** [comment]
Thanks for the reply.

I have found the original paper and its Matlab code but am finding it a bit difficult to reproduce it. I wish you good luck with your thesis.

Furthermore, thanks for mentioning my fork. I am not sure if I should send a pull request as the changes are very large compared to your code (including a lot of formatting and refactoring according to Python's PEP8 rules).

**Comment by Gabrock94** [comment]
> I have found the original paper and its Matlab code but am finding it a bit difficult to reproduce it. I wish you good luck with your thesis.

Yes, the code is not very self explanatory. Maybe now with LLMs converting it will be easier.

> Furthermore, thanks for mentioning my fork. I am not sure if I should send a pull request as the changes are very large compared to your code (including a lot of formatting and refactoring according to Python's PEP8 rules).
I'll leave this for you to decide
